server:
    port: 8080
    servlet:
      context-path: /pizzaexpress
    tomcat:
      accesslog:
        buffered: true
        directory: C:/logs
        enabled: true
        file-date-format: yyyy-MM-dd
        pattern: common
        prefix: access_log
        rename-on-rotate: false
        request-attributes-enabled: false
        rotate: true
        suffix: .log
spring:
    devtools:
       restart:
         enabled: false
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.102.214.64:3306/pizzaExpress?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      hikari:
        username: root
        password: 123456
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true