server:
    port: 8080
    servlet:
      context-path: /pizzaexpress
    tomcat:
      accesslog:
        buffered: true
        directory: C:/logs
        enabled: true
        file-date-format: yyyy-MM-dd
        pattern: common
        prefix: access_log
        rename-on-rotate: false
        request-attributes-enabled: false
        rotate: true
        suffix: .log
spring:
    devtools:
       restart:
         enabled: false
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pizzaExpress?characterEncoding=utf-8
      hikari:
        username: root
        password: QIAOYUNsts7..
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

logging:
    file: C:\logs\pizzaexpress.log


